appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: hO26wAWFVTpB0TlZ7gz5qKutH5MPFCIHE4mtHl59IqsK5bFfjJHzzXYI1j+aZcT3tDTZ25dRq0ZCwnOQiGqJE3dGfv5Ou8PKAHChVRCLJHXJ6pGYuFsUpthCnUFKEvYun/zaWd4ehLnpFGZtC2xPSt93Cmumd+6tMybw51uwXYL9RsqTynbs8AYLqZn3BK5JMJpuabuO9OAg8u+Ro/vinOdZdJMX6HCFtii9pLZnzxenqdT3FzchAPmgxMVztIeY2Z4D6C1Ze9AYkPoKVUMT6so8rMl0pNH4cgwNQUPM3xnwTh/H/ABbUN7qy29A7BoWsbldPcgS92zYGrstH6hBsGaxeSLvLqDFVMs0Aks7HZPFsz9QLn63S24KChoU7aRw+EZWuXtURPlmFNbE4iNeX4GvDtiDjIitWyShcR6TXLFIPUKOgaK6y1E7JPVxy6wd15jkoWXV+NQoY7tuL1w3HQ+qdXUpQ4qbiTe3XtAZiSATRebbfB3NoGKArp5oxK6zCQsmQiI0dcs6Iz/jMn/3SQce3r0Ygv/TDDyTHR/hoDpYf7gDB2y9IYxIuJEX35qfenrDf8Spi5BMylHaUO9p23gOvHNjwUHs816S8exdMA58ARSXku/RqftucbU+O9BDls0OVbUCViWnbVKUOOe0NTjFszKrkKBv2FeLwlYVzMU=}
provider:
  win: azure
bot:
  automerge: true
